services: 
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
      - ACCEPT_EULA=Y
      - MSSQL_PID=EXPRESS
      - SA_PASSWORD=Map197@123
    ports:
      - target: 1433
        published: 1433