// <auto-generated />
using System;
using BloodDonation.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonation.Infrastructures.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610173303_AddTableBloodCheck")]
    partial class AddTableBloodCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDonation.Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imageurls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodDonationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAntiHCVPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHBsAgPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHIVPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOtherInfectionsPositive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonationId")
                        .IsUnique();

                    b.HasIndex("BloodGroupId");

                    b.ToTable("BloodChecks");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaxStorageTemerature")
                        .HasColumnType("float");

                    b.Property<double>("MinStorageTemerature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShelfLifeInDay")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BloodComponents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b79"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4428),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Hồng cầu lắng",
                            ShelfLifeInDay = 35.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b78"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4435),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Khối hồng cầu có dung dịch bảo quản",
                            ShelfLifeInDay = 35.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b77"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4437),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Khối hồng cầu rửa (xử lý trong hệ thống hở)",
                            ShelfLifeInDay = 1.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b76"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4439),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Khối hồng cầu rửa (rửa trong hệ thống kín và có bổ sung dung dịch bảo quản hồng cầu)",
                            ShelfLifeInDay = 14.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b75"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4442),
                            IsDeleted = false,
                            MaxStorageTemerature = -60.0,
                            MinStorageTemerature = -80.0,
                            Name = "Khối hồng cầu đông lạnh",
                            ShelfLifeInDay = 365242199.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b74"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4444),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Khối tiểu cầu (Xử lí kín)",
                            ShelfLifeInDay = 5.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b73"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4447),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Khối tiểu cầu (Xử lí hở)",
                            ShelfLifeInDay = 0.25,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b72"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4449),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Khối tiểu cầu lọc bạch cầu (Xử lí kín)",
                            ShelfLifeInDay = 5.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b71"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4451),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Khối tiểu cầu lọc bạch cầu (Xử lí hở)",
                            ShelfLifeInDay = 0.25,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b70"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4456),
                            IsDeleted = false,
                            MaxStorageTemerature = -25.0,
                            MinStorageTemerature = -272.0,
                            Name = "Huyết tương đông lạnh",
                            ShelfLifeInDay = 2.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b69"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4458),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Huyết tương (Xử lí kín)",
                            ShelfLifeInDay = 14.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b68"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4460),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Huyết tương (Xử lí hở)",
                            ShelfLifeInDay = 1.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b67"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4463),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Tủa lạnh (Xử lí kín)",
                            ShelfLifeInDay = 14.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b66"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4465),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Tủa lạnh (Xử lí hở)",
                            ShelfLifeInDay = 1.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b65"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4467),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Khối bạch cầu hạt trung tính",
                            ShelfLifeInDay = 1.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b64"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4469),
                            IsDeleted = false,
                            MaxStorageTemerature = 6.0,
                            MinStorageTemerature = 2.0,
                            Name = "Máu toàn phần (Bảo quản)",
                            ShelfLifeInDay = 35.0,
                            Status = ""
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b63"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4471),
                            IsDeleted = false,
                            MaxStorageTemerature = 24.0,
                            MinStorageTemerature = 20.0,
                            Name = "Máu toàn phần",
                            ShelfLifeInDay = 1.0,
                            Status = ""
                        });
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodDonationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonationRequestId")
                        .IsUnique();

                    b.ToTable("BloodDonation");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DonatedDateRequest")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBloodTransfusionHistory")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDrugInjectionHistory")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecentIllnessOrMedication")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRecentSkinPenetrationOrSurgery")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVisitedEpidemicArea")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonReject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BloodDonationRequests");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RhFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BloodGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b83"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4344),
                            IsDeleted = false,
                            RhFactor = "+",
                            Type = "A"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b82"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4349),
                            IsDeleted = false,
                            RhFactor = "-",
                            Type = "A"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b81"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4353),
                            IsDeleted = false,
                            RhFactor = "+",
                            Type = "B"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b80"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4356),
                            IsDeleted = false,
                            RhFactor = "-",
                            Type = "B"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b7f"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4359),
                            IsDeleted = false,
                            RhFactor = "+",
                            Type = "AB"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b7e"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4361),
                            IsDeleted = false,
                            RhFactor = "-",
                            Type = "AB"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b7d"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4364),
                            IsDeleted = false,
                            RhFactor = "+",
                            Type = "O"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b7c"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4366),
                            IsDeleted = false,
                            RhFactor = "-",
                            Type = "O"
                        });
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodStorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIssue")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmergencyBloodRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BloodStorageId")
                        .IsUnique();

                    b.HasIndex("EmergencyBloodRequestId")
                        .IsUnique();

                    b.ToTable("BloodIssues");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodDonationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BloodGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BloodComponentId");

                    b.HasIndex("BloodDonationId")
                        .IsUnique();

                    b.HasIndex("BloodGroupId");

                    b.ToTable("BloodStorages");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.EmergencyBloodRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonReject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmergencyBloodRequests");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.HealthCheckForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("BloodDonateRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasChronicDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUnsafeSexualBehaviourOrSameSexSexualContact")
                        .HasColumnType("bit");

                    b.Property<double>("Hemoglobin")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInfectiousDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsedAlcoholRecently")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("VolumeBloodDonated")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonateRequestId")
                        .IsUnique();

                    b.ToTable("HealthCheckForms");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b86"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(3918),
                            IsDeleted = false,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b85"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4035),
                            IsDeleted = false,
                            Name = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("859a4997-1ffa-4915-b50e-9a99e4147b84"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2025, 6, 11, 0, 33, 3, 124, DateTimeKind.Local).AddTicks(4038),
                            IsDeleted = false,
                            Name = "NURSE"
                        });
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addresss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackUrlIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BloodGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontUrlIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.Blog", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodCheck", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodDonation", "BloodDonation")
                        .WithOne("BloodCheck")
                        .HasForeignKey("BloodDonation.Domain.Entities.BloodCheck", "BloodDonationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodDonation.Domain.Entities.BloodGroup", "BloodGroup")
                        .WithMany("BloodChecks")
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodDonation");

                    b.Navigation("BloodGroup");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonation", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodDonationRequest", "BloodDonationRequest")
                        .WithOne("BloodDonation")
                        .HasForeignKey("BloodDonation.Domain.Entities.BloodDonation", "BloodDonationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodDonationRequest");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonationRequest", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.User", "User")
                        .WithMany("BloodRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodIssue", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodStorage", "BloodStorage")
                        .WithOne("BloodIssue")
                        .HasForeignKey("BloodDonation.Domain.Entities.BloodIssue", "BloodStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.Domain.Entities.EmergencyBloodRequest", "EmergencyBloodRequest")
                        .WithOne("BloodIssue")
                        .HasForeignKey("BloodDonation.Domain.Entities.BloodIssue", "EmergencyBloodRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BloodStorage");

                    b.Navigation("EmergencyBloodRequest");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodStorage", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodComponent", "BloodComponent")
                        .WithMany("BloodStorages")
                        .HasForeignKey("BloodComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.Domain.Entities.BloodDonation", "BloodDonate")
                        .WithOne("BloodStorage")
                        .HasForeignKey("BloodDonation.Domain.Entities.BloodStorage", "BloodDonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonation.Domain.Entities.BloodGroup", "BloodGroup")
                        .WithMany("BloodStorages")
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BloodComponent");

                    b.Navigation("BloodDonate");

                    b.Navigation("BloodGroup");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.EmergencyBloodRequest", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.User", "User")
                        .WithMany("EmergencyBloodRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.HealthCheckForm", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodDonationRequest", "BloodDonationRequest")
                        .WithOne("HealthCheckForm")
                        .HasForeignKey("BloodDonation.Domain.Entities.HealthCheckForm", "BloodDonateRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BloodDonationRequest");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.User", b =>
                {
                    b.HasOne("BloodDonation.Domain.Entities.BloodGroup", "BloodGroup")
                        .WithMany("Users")
                        .HasForeignKey("BloodGroupId");

                    b.HasOne("BloodDonation.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodComponent", b =>
                {
                    b.Navigation("BloodStorages");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonation", b =>
                {
                    b.Navigation("BloodCheck");

                    b.Navigation("BloodStorage");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodDonationRequest", b =>
                {
                    b.Navigation("BloodDonation");

                    b.Navigation("HealthCheckForm");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodGroup", b =>
                {
                    b.Navigation("BloodChecks");

                    b.Navigation("BloodStorages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.BloodStorage", b =>
                {
                    b.Navigation("BloodIssue");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.EmergencyBloodRequest", b =>
                {
                    b.Navigation("BloodIssue");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BloodDonation.Domain.Entities.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("BloodRequests");

                    b.Navigation("EmergencyBloodRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
